# Generated by Django 4.2.8 on 2023-12-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0003_enquetes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquetes',
            name='enquete_aberta',
            field=models.BooleanField(default=True),
        ),
    ]
